AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    ascents-backend

    AWS repo for ascents-backend
    
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 10

Resources:

    AscentsFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: ascents/
            Handler: app.lambdaHandler
            Runtime: nodejs8.10
            Events:
                Ascents:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /ascents
                        Method: get

Outputs:

    AscentsApi:
      Description: "API Gateway endpoint URL for Prod stage for Ascents function"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ascents/"

    AscentsFunction:
      Description: "Ascents Lambda Function ARN"
      Value: !GetAtt AscentsFunction.Arn

    AscentsFunctionIamRole:
      Description: "Implicit IAM Role created for Ascents function"
      Value: !GetAtt AscentsFunctionRole.Arn
